version: "3"
services:
 registration-app:
   image: registration-app
   ports:
      - "8080:8080"
   networks:
    - springboot-mysql
   depends_on:
    - mysqldb
 mysqldb:
  image: mysql:8
  networks:
   - springboot-mysql
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=registrationdb
networks:
 springboot-mysql: